services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3x\StaticHtmlImporter\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  T3x\StaticHtmlImporter\Command\:
    resource: '../Classes/Command/*'
    public: true
    tags: ['console.command']
